#Verbose during prediction
verbose: False

img_size: 1024
epochs: 50
batch_size: 16

#for training
mode: 'train'
data: "datasets/all_data/pilsen.yaml"
output: "yolov8s_finetuned"
model: ultralyticsplus/yolov8s.pt
resume: False