#Verbose during prediction
verbose: False

img_size: 1024
epochs: 100
batch_size: 6

#for training
mode: 'train'
data: "datasets/all_data/railsem19.yaml"
output: "yolov8n_mot_ch"
model: ultralyticsplus/yolov8s.pt
resume: False